name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: Production
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: pbi-tools info
        run: |
          /app/pbi-tools/pbi-tools.core info

      - name: pbi-tools deploy (WhatIf)
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "Deploy from PBIX files" -whatIf
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

      - name: pbi-tools deploy
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "Deploy from PBIX files"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
